name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ashokxylo
          DOCKER_PASSWORD: A@shokak101299
          IMAGE_NAME: your-image-name
          VERSION: v${{ github.run_number }}
        run: |
          echo "Logging in to Docker Hub"
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

          echo "Building and pushing Docker image"
          docker build -t $IMAGE_NAME:$VERSION .
          docker push $IMAGE_NAME:$VERSION
