name: Build and Tag Docker Images

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ashokxylo -p A@shokak101299

      - name: Build and Tag Docker Image
        run: |
          docker build -t ashokxylo/kprui:latest .
          docker tag ashokxylo/kprui:latest ashokxylo/kprui:${{ github.sha }}
        working-directory: /home/runner/work/krp_trade/krp_trade/.Dockerfile

      - name: Push Docker Image
        run: |
          docker push ashokxylo/kprui:latest
          docker push ashokxylo/kprui:${{ github.sha }}
