name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'uat'
  workflow_dispatch:

  
jobs:
  build-container:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: ashokxylo # name of Docker Hub ID
      IMAGE_NAME: kprui
      IMAGE_TAG: ${{ github.run_number }}
      
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
  
    - name: Build Docker Image 
      run:
        docker build  . --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER --no-cache
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        image-ref: 'docker.io/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'MEDIUM,HIGH,CRITICAL'
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
  
    - name: Push Image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER

    - name: ssh-job
      uses: nekiro/ssh-job@v1.0.3
      with:
          host: 106.51.152.163
    # Port to use while connecting
          user: kafka
          password: Xyloinc@123
  deploy:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2     
      - name: Set up Kubectl 
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}      
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f Kubernetes/deployment.yaml.yml
        # Replace 'your-kubernetes-manifest.yml' with the path to your Kubernetes manifest.

      
        
