name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'uat'
  workflow_dispatch:

  
jobs:
  build-container:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: ashokxylo # name of Docker Hub ID
      IMAGE_NAME: kprui
      IMAGE_TAG: ${{ github.run_number }}
      
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
  
    - name: Build Docker Image 
      run:
        docker build  . --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER --no-cache
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        image-ref: 'docker.io/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'MEDIUM,HIGH,CRITICAL'
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
  
    - name: Push Image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER
        
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Kubernetes
        uses: azure/setup-k8s@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install my-app ./path/to/helm/chart
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG}}




      
        
