name: ci
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'uat'
  workflow_dispatch:

jobs:
  build-container:
    runs-on: self-hosted
    env:
      DOCKER_REPOSITORY: xyloincadmin
      IMAGE_NAME: trademanager
      IMAGE_TAG: ${{ github.run_number }}
      
    steps:
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
        
    - name: Build Docker Image 
      run:
        docker build  . --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER 
        
    - name: Push Image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER      
    
    - name: Git Checkout
      uses: actions/checkout@v2
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        image-ref: 'docker.io/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'MEDIUM,HIGH,CRITICAL'        
    -
        name: Checkout
        uses: actions/checkout@v3
     

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
         charts_dir: /kprchart
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"        

    - name: Configure kubectl
      uses: azure/setup-kubectl@v1
      with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
    - name: Deploy Helm chart
      run: |
          helm install trademanager kprchart
          helm template kprchart
    
