name: Deploy to Kubernetes

on:
  push:
    branches:
      - main # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        helm-version: 'v3.6.0' # Replace with your desired Helm version

    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install kprchart /kprchart
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
